config:
  # folder where the dump files will be stored
  dumpFolder: "./out"

  # optional: allows you to specify the max number of jobs to run at once
  jobLimit: 1

jobs:
  testRegex:
    # Database type: postgres, mysql
    dbType: postgres
    # Match method: regex, exact
    matchMethod: regex
    # Match string
    match: "^test-postgres"
    # Cron schedule
    cron: "*/5 * * * *"
    # optional: allows you to specify a custom db user for cmd to use
    dbUser: "postgres"

  # optional: you can specify multiple jobs

  textExact:
    dbType: postgres
    matchMethod: exact
    match: "postgres"
    cron: "*/5 * * * *"
