config:
  dumpFolder: "./out"

jobs:
  testRegex:
    # Database type: postgres, mysql
    dbType: postgres
    # Match method: regex, exact
    matchMethod: regex
    # Match string
    match: "^test-postgres"
    # Cron schedule
    cron: "*/5 * * * *"
    # allows you to specify a custom db user for cmd to use
    dbUser: "postgres"

  textExact:
    dbType: postgres
    matchMethod: exact
    match: "postgres"
    cron: "*/5 * * * *"
